ALTER TABLE encomenda ADD COLUMN IF NOT EXISTS data_retirada TIMESTAMP;
ALTER TABLE encomenda ADD COLUMN IF NOT EXISTS status_retirada VARCHAR(20) NOT NULL DEFAULT 'PENDENTE';
ALTER TABLE encomenda ADD COLUMN IF NOT EXISTS codigo_acesso VARCHAR(20);
ALTER TABLE encomenda ADD COLUMN IF NOT EXISTS data_expiracao_codigo TIMESTAMP;
